<article class="gallery">
  <p class="gallery-title">Gallery-5 Friends</p>
  <div class="modalphotos photogrid clearfix">
    <img src="images/gallery/friends/t01.jpg" alt="...">
    <img src="images/gallery/friends/t02.jpg" alt="...">
    <img src="images/gallery/friends/t03.jpg" alt="...">
    <img src="images/gallery/friends/t05.jpg" alt="...">
    <img src="images/gallery/friends/t06.jpg" alt="...">
    <img src="images/gallery/friends/t07.jpg" alt="...">
    <img src="images/gallery/friends/t08.jpg" alt="...">
    <img src="images/gallery/friends/t09.jpg" alt="...">
    <img src="images/gallery/friends/t10.jpg" alt="...">
    <img src="images/gallery/friends/t11.jpg" alt="...">
    <img src="images/gallery/friends/t12.jpg" alt="...">
    <img src="images/gallery/friends/t13.jpg" alt="...">
    <img src="images/gallery/friends/t14.jpg" alt="...">
    <img src="images/gallery/friends/t15.jpg" alt="...">
    <img src="images/gallery/friends/t16.jpg" alt="...">
    <img src="images/gallery/friends/t17.jpg" alt="...">
    <img src="images/gallery/friends/t18.jpg" alt="...">
    <img src="images/gallery/friends/t19.jpg" alt="...">
    <img src="images/gallery/friends/t20.jpg" alt="...">
    <img src="images/gallery/friends/t21.jpg" alt="...">
    <img src="images/gallery/friends/t22.jpg" alt="...">
    <img src="images/gallery/friends/t23.jpg" alt="...">
    <img src="images/gallery/friends/t24.jpg" alt="...">
    <img src="images/gallery/friends/t25.jpg" alt="...">
    <img src="images/gallery/friends/t26.jpg" alt="...">
    <img src="images/gallery/friends/t27.jpg" alt="...">
    <img src="images/gallery/friends/t28.jpg" alt="...">
    <img src="images/gallery/friends/t29.jpg" alt="...">
    <img src="images/gallery/friends/t30.jpg" alt="...">
    <img src="images/gallery/friends/t31.jpg" alt="...">
    <img src="images/gallery/friends/t32.jpg" alt="...">
    <img src="images/gallery/friends/t33.jpg" alt="...">
    <img src="images/gallery/friends/t34.jpg" alt="...">
    <img src="images/gallery/friends/t35.jpg" alt="...">
    <img src="images/gallery/friends/t36.jpg" alt="...">
    <img src="images/gallery/friends/t37.jpg" alt="...">
    <img src="images/gallery/friends/t38.jpg" alt="...">
    <img src="images/gallery/friends/t39.jpg" alt="...">
    <img src="images/gallery/friends/t40.jpg" alt="...">
    <img src="images/gallery/friends/t41.jpg" alt="...">
    <img src="images/gallery/friends/t42.jpg" alt="...">
    <img src="images/gallery/friends/t43.jpg" alt="...">
    <img src="images/gallery/friends/t44.jpg" alt="...">
  </div>
</article><!-- home -->
